// Generated by @codexsun/app-cli. Do not edit manually.

export type MdiCatalogApplication = {
  icon: string;
  id: string;
  label: string;
  localUrlKey: string;
  path: string;
};

export const mdiCatalogApplications: readonly MdiCatalogApplication[] = [
  {
    "icon": "application",
    "id": "accounts",
    "label": "Accounts",
    "localUrlKey": "VITE_ACCOUNTS_WEB_URL",
    "path": "/"
  },
  {
    "icon": "application",
    "id": "auditor",
    "label": "Auditor",
    "localUrlKey": "VITE_AUDITOR_WEB_URL",
    "path": "/"
  },
  {
    "icon": "application",
    "id": "billing",
    "label": "Billing",
    "localUrlKey": "VITE_BILLING_WEB_URL",
    "path": "/"
  },
  {
    "icon": "application",
    "id": "codeitz",
    "label": "Codeitz",
    "localUrlKey": "VITE_CODEITZ_WEB_URL",
    "path": "/"
  },
  {
    "icon": "application",
    "id": "crm",
    "label": "CRM",
    "localUrlKey": "VITE_CRM_WEB_URL",
    "path": "/"
  },
  {
    "icon": "application",
    "id": "cxforge",
    "label": "CXForge",
    "localUrlKey": "VITE_CXFORGE_WEB_URL",
    "path": "/"
  },
  {
    "icon": "application",
    "id": "docx",
    "label": "DOCX",
    "localUrlKey": "VITE_DOCX_WEB_URL",
    "path": "/"
  },
  {
    "icon": "application",
    "id": "ecommerce",
    "label": "Ecommerce",
    "localUrlKey": "VITE_ECOMMERCE_WEB_URL",
    "path": "/"
  },
  {
    "icon": "application",
    "id": "garments",
    "label": "Garments",
    "localUrlKey": "VITE_GARMENTS_WEB_URL",
    "path": "/"
  },
  {
    "icon": "application",
    "id": "himsx",
    "label": "HIMSX",
    "localUrlKey": "VITE_HIMSX_WEB_URL",
    "path": "/"
  },
  {
    "icon": "application",
    "id": "hrms",
    "label": "HRMS",
    "localUrlKey": "VITE_HRMS_WEB_URL",
    "path": "/"
  },
  {
    "icon": "application",
    "id": "lms",
    "label": "LMS",
    "localUrlKey": "VITE_LMS_WEB_URL",
    "path": "/"
  },
  {
    "icon": "application",
    "id": "orship",
    "label": "Orship",
    "localUrlKey": "VITE_ORSHIP_WEB_URL",
    "path": "/"
  },
  {
    "icon": "platform",
    "id": "platform",
    "label": "Platform",
    "localUrlKey": "VITE_PLATFORM_WEB_URL",
    "path": "/system"
  },
  {
    "icon": "application",
    "id": "projex",
    "label": "Projex",
    "localUrlKey": "VITE_PROJEX_WEB_URL",
    "path": "/"
  },
  {
    "icon": "application",
    "id": "qcafe",
    "label": "Q Cafe",
    "localUrlKey": "VITE_QCAFE_WEB_URL",
    "path": "/"
  },
  {
    "icon": "application",
    "id": "sites",
    "label": "Sites",
    "localUrlKey": "VITE_SITES_WEB_URL",
    "path": "/"
  },
  {
    "icon": "uiux",
    "id": "uiux",
    "label": "UIUX",
    "localUrlKey": "VITE_UIUX_WEB_URL",
    "path": "/"
  },
  {
    "icon": "zetro",
    "id": "zetro",
    "label": "Zetro",
    "localUrlKey": "VITE_ZETRO_WEB_URL",
    "path": "/zetro"
  },
  {
    "icon": "application",
    "id": "zuno",
    "label": "Zuno",
    "localUrlKey": "VITE_ZUNO_WEB_URL",
    "path": "/"
  }
] as const;
